/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-09-26 16:27:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"./css/index.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("   <title>sdCommunity</title>\r\n");
      out.write("   \r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("   	.back-fist-part{\r\n");
      out.write("		background-image: url(\"./css/img/bg-stars-1.webp\");\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("    	background-position: center;\r\n");
      out.write("    	background-size: cover;\r\n");
      out.write(" 		width: 100%;\r\n");
      out.write("    	height: auto;	\r\n");
      out.write("	}\r\n");
      out.write("	.world{\r\n");
      out.write("		background-image: url(\"./img/worldrotate.png\");\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("    	background-position: center;\r\n");
      out.write("    	background-size: cover;\r\n");
      out.write(" 		width: 100%;\r\n");
      out.write("    	height: 500px;	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bdy\">\r\n");
      out.write("<img alt=\"\" src=\"./img/logo.png\" style=\"width: 150px;\"> \r\n");
      out.write("<ul class=\"nav  justify-content-end\" style=\"margin-top: -140px;\" >\r\n");
      out.write("	\r\n");
      out.write("  <li class=\"nav-item\">\r\n");
      out.write("    <a class=\"nav-link active\" aria-current=\"page\"  href=\"Login.jsp\"><span style=\" padding: inherit;\r\n");
      out.write("    background: #33495d00;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-transform: uppercase;\">Login</span></a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item\">\r\n");
      out.write("    <a class=\"nav-link\" href=\"signup.jsp\"><span style=\" padding: inherit;\r\n");
      out.write("    background: #33495d00;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-transform: uppercase;\">Sign up</span></a>\r\n");
      out.write("  </li>\r\n");
      out.write("</ul>\r\n");
      out.write("		\r\n");
      out.write("	<div class=\"back-fist-part\">	\r\n");
      out.write("	<div class=\"container-xl\">\r\n");
      out.write("  <!-- Content here -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("	    	\r\n");
      out.write("	    	<div class=\"col-8\">\r\n");
      out.write("	    	\r\n");
      out.write("	    		<figure class=\"heading-possision\">\r\n");
      out.write("	    			<h1 class=\"animate-charcter\">sdCommunity</h1>\r\n");
      out.write("	  				<blockquote class=\"blockquote\">\r\n");
      out.write("	    				<p>The sdComunity project proposes the creation of a specialized social network tailored exclusively for developers. This platform aims to facilitate seamless knowledge sharing, problem-solving, and community building within the global developer community. The decision to embark on this endeavor is grounded in several compelling reasons.\r\n");
      out.write("						</p>\r\n");
      out.write("	 				 </blockquote>\r\n");
      out.write("					  <figcaption class=\"blockquote-footer\">\r\n");
      out.write("					    Social network platform for \r\n");
      out.write("					     <cite title=\"Source Title\"> Developers</cite>\r\n");
      out.write("					  </figcaption>\r\n");
      out.write("				</figure>\r\n");
      out.write("	    		\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    	<div class=\"col\">\r\n");
      out.write("	    		\r\n");
      out.write("	    			<img class=\"homeFirstImg\" alt=\"\" src=\"./img/Idea.png\">\r\n");
      out.write("	    		\r\n");
      out.write("	    	</div>\r\n");
      out.write("	  	</div>\r\n");
      out.write("  	</div>\r\n");
      out.write("  	</div>\r\n");
      out.write("  	<div class=\"container-xl\">\r\n");
      out.write("  <!-- Content here -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"back-fist-part\">\r\n");
      out.write("		<div class=\"row world\" >\r\n");
      out.write("	    	<div class=\"col\" >\r\n");
      out.write("	    		\r\n");
      out.write("	    		\r\n");
      out.write("	    		\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    	\r\n");
      out.write("	    	<div class=\"col-3\">\r\n");
      out.write("	    		\r\n");
      out.write("	    		\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    	\r\n");
      out.write("	    	<div class=\"col\">\r\n");
      out.write("	    		\r\n");
      out.write("	    	</div>\r\n");
      out.write("	  	</div>\r\n");
      out.write("  	</div>\r\n");
      out.write("  	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container-xl \" id=\"homeThird\">\r\n");
      out.write("		<div class=\"back-fist-part\">\r\n");
      out.write("  		<!-- Stack the columns on mobile by making one full-width and the other half-width -->\r\n");
      out.write("  			<div class=\"row\">\r\n");
      out.write("			    <div class=\"col-md-8\">\r\n");
      out.write("			    	<div class=\"homeThredContent\">\r\n");
      out.write("					     <div class=\"waviy\">\r\n");
      out.write("							   <span style=\"--i:1\">C</span>\r\n");
      out.write("							   <span style=\"--i:2\">o</span>\r\n");
      out.write("							   <span style=\"--i:3\">n</span>\r\n");
      out.write("							   <span style=\"--i:4\">n</span>\r\n");
      out.write("							   <span style=\"--i:5\">e</span>\r\n");
      out.write("							   <span style=\"--i:6\">c</span>\r\n");
      out.write("							   <span style=\"--i:7\">t</span>\r\n");
      out.write("							   <span style=\"--i:8\">i</span>\r\n");
      out.write("							   <span style=\"--i:9\">n</span>\r\n");
      out.write("							   <span style=\"--i:10\">g</span>\r\n");
      out.write("							   <span style=\"--i:11\"><br></span>\r\n");
      out.write("							   <span style=\"--i:12\">w</span>\r\n");
      out.write("							   <span style=\"--i:13\">o</span>\r\n");
      out.write("							   <span style=\"--i:14\">r</span>\r\n");
      out.write("							   <span style=\"--i:15\">l</span>\r\n");
      out.write("							   <span style=\"--i:16\">d</span>\r\n");
      out.write("		  				</div>\r\n");
      out.write(" 					 </div>\r\n");
      out.write(" 					 <p  style=\"font-size: 15px\" >The sdCommunity project brings forth a specialized social network uniquely designed for developers, presenting a dedicated space for knowledge exchange, collaborative problem-solving, and fostering a tightly-knit global developer community. This endeavor stands out for its ability to unite developers worldwide in a seamless platform, transcending geographical boundaries and time zones. By streamlining the process of sharing insights, seeking advice, and engaging in meaningful discussions, the network offers a pivotal resource for professional growth and innovation. Moreover, the platform's niche focus ensures that content remains highly relevant, enhancing the overall quality and effectiveness of interactions. With an emphasis on expertise and collaboration, sdCommunity is poised to revolutionize how developers connect and learn from one another, ultimately advancing the field of software development.</p>\r\n");
      out.write("			    \r\n");
      out.write("			     </div>\r\n");
      out.write("			    <div class=\"col\" id=\"homeThirdPart\">\r\n");
      out.write("			    \r\n");
      out.write("			    </div>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			</div>\r\n");
      out.write("  		</div>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
