/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-09-29 17:07:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserPost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');


Integer id =(Integer)session.getAttribute("uid");
String fname=(String)session.getAttribute("fname"); 
String lname=(String)session.getAttribute("lname"); 
String email=(String)session.getAttribute("email");
Integer num=(Integer)session.getAttribute("num");
String company = (String) session.getAttribute("company");
String github = (String) session.getAttribute("github");
String linkedin = (String) session.getAttribute("linkedin");
String website = (String) session.getAttribute("website");
String nation = (String) session.getAttribute("nation");
String gender = (String) session.getAttribute("gender");
String about = (String) session.getAttribute("about");
String college = (String) session.getAttribute("college");
String position = (String) session.getAttribute("position");


      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./homecss/style.css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<title>Post</title>\r\n");
      out.write("<style>\r\n");
      out.write("		\r\n");
      out.write("    .post-form {\r\n");
      out.write("        max-width: 600px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        background-color: #5f5fd13b;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("    input, textarea, select {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    button {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        background-color: #007bff;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    button:hover {\r\n");
      out.write("        background-color: #0056b3;\r\n");
      out.write("    }\r\n");
      out.write("    .format-options {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .post-display {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .profileImg{\r\n");
      out.write("		height: 250px;\r\n");
      out.write("		border: 1 solid white; \r\n");
      out.write("	}\r\n");
      out.write("	#center{\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#showCode, #showText, #showCode {\r\n");
      out.write("			height: 119px;\r\n");
      out.write("		    background-color: transparent;\r\n");
      out.write("		    border: 1px solid #ccc;\r\n");
      out.write("		    border-radius: 4px;\r\n");
      out.write("		    padding: 10px;\r\n");
      out.write("		    font-family: 'Courier New', monospace;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hbdy\" style=\"background-color: black; color: white;\">\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		  <div class=\"modal-dialog\" style=\"color: black;\">\r\n");
      out.write("		    <div class=\"modal-content\">\r\n");
      out.write("		      <div class=\"modal-header\">\r\n");
      out.write("		        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Modal title</h1>\r\n");
      out.write("		        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <form action=\"settingsAccess\" method=\"post\">\r\n");
      out.write("		      <div class=\"modal-body\">\r\n");
      out.write("		        <div class=\"mb-3\">\r\n");
      out.write("    				<label for=\"exampleInputPassword1\" class=\"form-label\">Password</label>\r\n");
      out.write("    				<input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" name=\"exampleInputPassword1\">\r\n");
      out.write("  				</div>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-footer\">\r\n");
      out.write("		        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("		         <input type=\"submit\" class=\"btn btn-primary\" value=\"OK\">\r\n");
      out.write("		      </div>\r\n");
      out.write("		      </form>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	<ul class=\"nav justify-content-end \">\r\n");
      out.write("		<li class=\"nav-item\">\r\n");
      out.write("		    	<a class='nav-link' href='UserHome.jsp'>Home</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav-item\">\r\n");
      out.write("		    ");

		  	if (email != null){
		  		out.print("<a class='nav-link' href=''>Post</a>");
		  	}else{
		  		out.print("");
		  	}
		  
      out.write("\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav-item\">\r\n");
      out.write("		    ");

		  	if (email != null){
		  		out.print("<a class='nav-link' href=''>Followers</a>");
		  	}else{
		  		out.print("");
		  	}
		  
      out.write("\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav-item\">\r\n");
      out.write("		    ");

		  	if (email != null){
		  		out.print("<a class='nav-link' href=''>Chat</a>");
		  	}else{
		  		out.print("");
		  	}
		  
      out.write("\r\n");
      out.write("		  </li>\r\n");
      out.write("		  \r\n");
      out.write("		  <li class=\"nav-item\">\r\n");
      out.write("		   ");

		  	if (email != null){
		  		out.print("<a class='nav-link' data-bs-toggle='modal' data-bs-target='#exampleModal'>Settings</a>");
		  	}else{
		  		out.print("");
		  	}
		  
      out.write("\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav-item\">\r\n");
      out.write("		  ");

		  	if (email != null){
		  		if (company != null){
		  			out.print("<a class='nav-link' href='viewProfile.jsp'>Profile</a>");
		  		}
		  		else{
		  			out.print("<a class='nav-link' href='profile.jsp'>Profile</a>");
		  		}
		  		
		  	}else{
		  		out.print("<a class='nav-link' href='Login.jsp'>Login</a>");
		  	}
		  
      out.write("\r\n");
      out.write("		  </li>\r\n");
      out.write("		  \r\n");
      out.write("		  <li class=\"nav-item\">\r\n");
      out.write("		    ");

		  	if (email != null){
		  		out.print("<a class='nav-link' href='logout.jsp'>Logout</a>");
		  	}else{
		  		out.print("");
		  	}
		  
      out.write("\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav-item\">\r\n");
      out.write("		  ");

		  	if (email != null){
		  		if (company != null){
		  			out.print("<a class='nav-link' href='viewProfile.jsp'><img alt='' src='image?id="+id+"' style=' width: 35px; border-radius: 50%; height: 35px;border: 1px solid white;'/></a>");
		  		}
		  		else{
		  			out.print("<a class='nav-link' href='viewProfile.jsp'><img alt='' src='./homecss/img/User-Profile.png'style=' width: 35px; border-radius: 50%; height: 35px;border: 1px solid white;'/></a>");
		  		}
		  	}else{
		  		out.print("");
		  	}
		  
      out.write("\r\n");
      out.write("		  </li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<div class=\"container-xl\" style=\"color: white; margin-top: 20px;\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("	  \r\n");
      out.write("	<div class=\"col\">\r\n");
      out.write("    <div class=\"post-form\">\r\n");
      out.write("        <h2>Create Your Post</h2>\r\n");
      out.write("        <form action=\"postServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        	<label for=\"heading\">Heading:</label>\r\n");
      out.write("        	<input type=\"text\" name=\"heading\" id=\"heading\" required=\"required\" ><br>\r\n");
      out.write("            <label for=\"image\">Upload Screen Shoot:</label>\r\n");
      out.write("            <input type=\"file\" id=\"image\" name=\"image\" accept=\"image/*\" onchange=\"displayImage()\"><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"link\">Paste your link:</label>\r\n");
      out.write("            <input type=\"url\" id=\"link\" name=\"link\" oninput=\"updateLink()\"><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"text\">Post Text:</label>\r\n");
      out.write("            <textarea id=\"text\" name=\"text\" rows=\"3\" oninput=\"updateText()\" required=\"required\"></textarea><br>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"format-options\">\r\n");
      out.write("                <button type=\"button\" onclick=\"makeBold()\">Bold</button>\r\n");
      out.write("                <button type=\"button\" onclick=\"makeItalic()\">Italic</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"code\">Programming Code:</label>\r\n");
      out.write("            <textarea id=\"code\" name=\"code\" rows=\"3	\" oninput=\"updateCode()\"></textarea><br>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Post</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	    <div class=\"col\">\r\n");
      out.write("			<div id=\"center\">\r\n");
      out.write("			 <img class=\"profileImg\" alt=\"\" src=\"./homecss/img/bg-stars-1.webp\" id=\"updatedImg\" style=\"width: 90%;\"/><br>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <h5>Link :</h5>\r\n");
      out.write("		    <a href=\"\" id=\"showLink\"></a>\r\n");
      out.write("		    <h5>Post :</h5>\r\n");
      out.write("		    <p id=\"showText\"></p>\r\n");
      out.write("		    <h5>Code :</h5>\r\n");
      out.write("		    <pre id=\"showCode\"></pre>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function makeBold() {\r\n");
      out.write("            var textarea = document.getElementById('text');\r\n");
      out.write("            var selectedText = textarea.value.substring(textarea.selectionStart, textarea.selectionEnd);\r\n");
      out.write("            var beforeText = textarea.value.substring(0, textarea.selectionStart);\r\n");
      out.write("            var afterText = textarea.value.substring(textarea.selectionEnd);\r\n");
      out.write("            textarea.value = beforeText + '<b>' + selectedText + '</b>' + afterText;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function makeItalic() {\r\n");
      out.write("            var textarea = document.getElementById('text');\r\n");
      out.write("            var selectedText = textarea.value.substring(textarea.selectionStart, textarea.selectionEnd);\r\n");
      out.write("            var beforeText = textarea.value.substring(0, textarea.selectionStart);\r\n");
      out.write("            var afterText = textarea.value.substring(textarea.selectionEnd);\r\n");
      out.write("            textarea.value = beforeText + '<i>' + selectedText + '</i>' + afterText;\r\n");
      out.write("        }\r\n");
      out.write("        var image = document.getElementById('image').value;\r\n");
      out.write("        var link = document.getElementById('link').value;\r\n");
      out.write("        var text = document.getElementById('text').value;\r\n");
      out.write("        var code = document.getElementById('code').value;\r\n");
      out.write("        var codeLength = code.length;\r\n");
      out.write("        console.log(\"The length of the code is:\", codeLength);\r\n");
      out.write("        \r\n");
      out.write("        function displayImage() {\r\n");
      out.write("        	var input = document.getElementById('image');\r\n");
      out.write("        	var img = document.getElementById('updatedImg');\r\n");
      out.write("\r\n");
      out.write("        	var file = input.files[0];\r\n");
      out.write("        	var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("        	if (!file) {\r\n");
      out.write("        	img.src = \"./css/img/User-profile.png\"; // Set default image source\r\n");
      out.write("        	return;\r\n");
      out.write("        	}\r\n");
      out.write("\r\n");
      out.write("        	if (file.size > 85 * 1024) { // Check if image size is greater than 200KB\r\n");
      out.write("        	document.getElementById(\"imgError\").innerHTML = \"Please update image size lesthan 85kb\";\r\n");
      out.write("        	input.value = \"\"; // Clear the input field\r\n");
      out.write("        	img.src = \"./css/img/User-profile.png\"; // Set default image source\r\n");
      out.write("        	return;\r\n");
      out.write("        	}\r\n");
      out.write("\r\n");
      out.write("        	reader.onload = function(e) {\r\n");
      out.write("        	img.src = e.target.result;\r\n");
      out.write("        	}\r\n");
      out.write("\r\n");
      out.write("        	reader.readAsDataURL(file);\r\n");
      out.write("        }\r\n");
      out.write("        function updateCode() {\r\n");
      out.write("            var inputCode = document.getElementById('code').value;\r\n");
      out.write("            var showCode = document.getElementById('showCode');\r\n");
      out.write("            showCode.textContent = inputCode;\r\n");
      out.write("        }\r\n");
      out.write("        function updateLink() {\r\n");
      out.write("            var inputLink = document.getElementById('link').value;\r\n");
      out.write("            var showLink = document.getElementById('showLink');\r\n");
      out.write("            showLink.href = inputLink;\r\n");
      out.write("            showLink.textContent = inputLink;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function updateText() {\r\n");
      out.write("            var inputText = document.getElementById('text').value;\r\n");
      out.write("            var showText = document.getElementById('showText');\r\n");
      out.write("            showText.textContent = inputText;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
